-- Generated by `npm run keys` from lib/scenes.ts and lib/questions.ts. Do not edit by hand.
-- Replaces every answer key at once. Safe to run any number of times.
-- Answers already saved in old rooms are not moved; start a fresh run from the first question.

begin;

delete from public.answer_keys;

insert into public.answer_keys (scene_index, correct, multi) values
  (5, array['physician', 'dentist', 'vet', 'radtech', 'physicist', 'radofficer'], true), -- s02
  (9, array['patient'], false), -- s04
  (11, array['C'], false), -- s06
  (13, array['collar_out'], false), -- s08
  (14, array['assess'], false); -- s09

commit;

select scene_index, correct from public.answer_keys order by 1;
