// Writes supabase/answer_keys.sql: every answer key at the scene index lib/scenes.ts gives it today,
// with the answers from lib/questions.ts. Run `npm run keys` after the slides are final, then run the SQL once.
import { writeFileSync } from "node:fs";
import { SCENES } from "../lib/scenes.ts";
import { QUESTIONS } from "../lib/questions.ts";

const q = (s) => `'${s.replace(/'/g, "''")}'`;
const keys = SCENES.flatMap((scene, index) => {
  const question = QUESTIONS[scene.id];
  return question ? [{ index, id: scene.id, question }] : [];
});
const rows = keys.map(
  ({ index, id, question }, i) =>
    `  (${index}, array[${question.correct.map(q).join(", ")}], ${!!question.multi})${i < keys.length - 1 ? "," : ";"} -- ${id}`,
);

const sql = `-- Generated by \`npm run keys\` from lib/scenes.ts and lib/questions.ts. Do not edit by hand.
-- Replaces every answer key at once. Safe to run any number of times.
-- Answers already saved in old rooms are not moved; start a fresh run from the first question.

begin;

delete from public.answer_keys;

insert into public.answer_keys (scene_index, correct, multi) values
${rows.join("\n")}

commit;

select scene_index, correct from public.answer_keys order by 1;
`;

writeFileSync(new URL("../supabase/answer_keys.sql", import.meta.url), sql);
console.log(sql);
